name: Merge main & staging in same time

on:
  pull_request_target:
      types: [ closed ]
  push:
    branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          # Stage the file, commit and push
          git fetch
          git checkout staging
          git reset --hard origin/main
          git push -f origin staging
