name: Push force on staging in same time that main

on:
  push:
    branches:
      - master
  pull_request_target:
    types: [ closed ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          # Stage the file, commit and push
          git fetch
          git checkout staging
          git reset --hard origin/master
          git push -f origin staging
