name: Merge main & staging in same time

on:
  push:
    branches:
      - main
  pull_request:
    types: [ closed ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          # Stage the file, commit and push
          git fetch
          git checkout staging
          git reset --hard origin/main
          git push -f origin staging
